language: python
python:
  - "2.7"
  - "3.3"
env:
  matrix:
   - DJANGO_VERSION=1.4
   - DJANGO_VERSION=1.7
   - DJANGO_VERSION=1.8
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq sloccount
install:
  - npm install -g bower
  - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
  - pip install -U .
  - pip install -U -r requirements_dev.txt
  - pip install pep8
  - pip install coviolations_app
script:
  - mkdir /home/travis/test_root/ -p
  - export TEST_PROJECT_ROOT=/home/travis/test_root/
  - coverage run runtests.py test djangobower 2>test_out
after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
  - covio
