language: python
python:
  - "2.7"
  - "3.3"
install:
  - npm install -g bower
  - pip install . --use-mirrors
script:
  - mkdir /home/travis/test_root/ -p
  - export TEST_PROJECT_ROOT=/home/travis/test_root/
  - django-admin.py test --settings=djangobower.test_settings djangobower
