language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install . --use-mirrors
script:
  - TEST_PROJECT_ROOT=/home/travis/ django-admin.py test --settings=djangobower.test_settings djangobower
